version: '3'
services:
  php:
    build:
      context: ./docker/php
    user: "1000:1000"
    env_file:
      - ./etc/environment.yml
    volumes:
      - './:/var/www/html'
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - './:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    depends_on:
      - php

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'